default_language_version:
  python: "3.13"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.13.1"
    hooks:
      - id: ruff-format
      - id: ruff-check
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: ty check . --ignore unresolved-import
        language: python
